"use client";

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "~/components/ui/dialog";
import { Button } from "~/components/ui/button";

interface TransactionReceiptProps {
  isOpen: boolean;
  onClose: () => void;
  transaction: {
    id: string;
    reference: string;
    type: string;
    amount: number;
    status: string;
    description?: string | null;
    recipient?: string | null;
    symbol?: string | null;
    metadata?: Record<string, unknown> | null;
    createdAt: Date | string;
  } | null;
}

export function TransactionReceipt({
  isOpen,
  onClose,
  transaction,
}: TransactionReceiptProps) {
  if (!transaction) return null;

  const isOutgoing = transaction.amount < 0 ||
    ["investment", "bill_pay", "send"].includes(transaction.type);

  const displayAmount = Math.abs(transaction.amount);
  const formattedDate = new Date(transaction.createdAt).toLocaleString();

  const getTypeLabel = (type: string) => {
    switch (type) {
      case "investment": return "Investment";
      case "bill_pay": return "Bill Payment";
      case "send": return "Send";
      case "receive": return "Receive";
      case "payroll": return "Payroll";
      default: return type;
    }
  };

  const getTypeIcon = (type: string) => {
    switch (type) {
      case "investment": return "📈";
      case "bill_pay": return "📄";
      case "send": return "↗️";
      case "receive": return "↙️";
      case "payroll": return "💰";
      default: return "💳";
    }
  };

  const handleDownload = () => {
    const receiptText = `
GRID TRANSACTION RECEIPT
========================

Reference: ${transaction.reference}
Type: ${getTypeLabel(transaction.type)}
Amount: ${isOutgoing ? "-" : "+"}$${displayAmount.toFixed(2)} USDC
Status: ${transaction.status.toUpperCase()}
Date: ${formattedDate}
${transaction.description ? `Description: ${transaction.description}` : ""}
${transaction.recipient ? `Recipient: ${transaction.recipient}` : ""}
${transaction.symbol ? `Asset: ${transaction.symbol}` : ""}

Transaction ID: ${transaction.id}
Network: Tempo Network

========================
Generated by Grid
    `.trim();

    const blob = new Blob([receiptText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `receipt-${transaction.reference}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleShare = async () => {
    const shareData = {
      title: "Grid Transaction Receipt",
      text: `Transaction ${transaction.reference}: ${isOutgoing ? "-" : "+"}$${displayAmount.toFixed(2)} USDC`,
      url: window.location.href,
    };

    if (navigator.share) {
      try {
        await navigator.share(shareData);
      } catch (err) {
        console.log("Share cancelled");
      }
    } else {
      await navigator.clipboard.writeText(
        `Grid Receipt: ${transaction.reference} - ${isOutgoing ? "-" : "+"}$${displayAmount.toFixed(2)} USDC`
      );
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="rounded-xl max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <span className="text-2xl">{getTypeIcon(transaction.type)}</span>
            Transaction Receipt
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          {/* Status Badge */}
          <div className="flex justify-center">
            <span
              className={`px-3 py-1 rounded-full text-sm font-medium ${
                transaction.status === "confirmed"
                  ? "bg-green-100 text-green-700"
                  : transaction.status === "pending"
                  ? "bg-yellow-100 text-yellow-700"
                  : "bg-red-100 text-red-700"
              }`}
            >
              {transaction.status === "confirmed" && "✓ "}
              {transaction.status.charAt(0).toUpperCase() + transaction.status.slice(1)}
            </span>
          </div>

          {/* Amount */}
          <div className="text-center p-4 bg-slate-50 rounded-xl">
            <p className="text-sm text-slate-500 mb-1">{getTypeLabel(transaction.type)}</p>
            <p
              className={`text-3xl font-bold ${
                isOutgoing ? "text-slate-900" : "text-green-600"
              }`}
            >
              {isOutgoing ? "-" : "+"}${displayAmount.toFixed(2)}
              <span className="text-lg text-slate-500 ml-1">USDC</span>
            </p>
          </div>

          {/* Details */}
          <div className="space-y-3 text-sm">
            <div className="flex justify-between py-2 border-b border-slate-100">
              <span className="text-slate-500">Reference</span>
              <span className="font-mono text-slate-900">{transaction.reference}</span>
            </div>

            {transaction.description && (
              <div className="flex justify-between py-2 border-b border-slate-100">
                <span className="text-slate-500">Description</span>
                <span className="text-slate-900 text-right max-w-[120px] sm:max-w-[200px] truncate">
                  {transaction.description}
                </span>
              </div>
            )}

            {transaction.recipient && (
              <div className="flex justify-between py-2 border-b border-slate-100">
                <span className="text-slate-500">Recipient</span>
                <span className="text-slate-900 text-right max-w-[120px] sm:max-w-[200px] truncate">
                  {transaction.recipient}
                </span>
              </div>
            )}

            {transaction.symbol && (
              <div className="flex justify-between py-2 border-b border-slate-100">
                <span className="text-slate-500">Asset</span>
                <span className="text-slate-900">{transaction.symbol}</span>
              </div>
            )}

            <div className="flex justify-between py-2 border-b border-slate-100">
              <span className="text-slate-500">Date & Time</span>
              <span className="text-slate-900">{formattedDate}</span>
            </div>

            <div className="flex justify-between py-2 border-b border-slate-100">
              <span className="text-slate-500">Network</span>
              <span className="text-slate-900">Tempo Network</span>
            </div>

            <div className="flex justify-between py-2">
              <span className="text-slate-500">Transaction ID</span>
              <span className="font-mono text-xs text-slate-600 max-w-[180px] truncate">
                {transaction.id}
              </span>
            </div>
          </div>

          {/* Actions */}
          <div className="flex gap-2 pt-2">
            <Button
              variant="outline"
              onClick={handleDownload}
              className="flex-1 rounded-xl"
            >
              <svg
                className="w-4 h-4 mr-2"
                fill="none"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path>
              </svg>
              Download
            </Button>
            <Button
              onClick={handleShare}
              className="flex-1 bg-black hover:bg-slate-800 text-white rounded-xl"
            >
              <svg
                className="w-4 h-4 mr-2"
                fill="none"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z"></path>
              </svg>
              Share
            </Button>
          </div>

          <Button
            variant="ghost"
            onClick={onClose}
            className="w-full rounded-xl"
          >
            Close
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
